dxc-technology/csc-agility-platform-sdk

- io/src/main/java/com/servicemesh/io/http/IHttpClientConfig.java
- io/src/main/java/com/servicemesh/io/http/IHttpClientConfigBuilder.java
- io/src/main/java/com/servicemesh/io/http/impl/DefaultHttpClient.java
- io/src/main/java/com/servicemesh/io/http/impl/DefaultHttpClientConfig.java
- io/src/main/java/com/servicemesh/io/http/impl/DefaultHttpClientConfigBuilder.java
- io/src/test/java/com/servicemesh/io/http/HttpClientTest.java
- ivy.xml
- pom.xml
> US6113 Allow configuration of manual cookie management

- io/src/main/java/com/servicemesh/io/http/QueryParams.java
- io/src/test/java/com/servicemesh/io/http/QueryParamsTest.java
As part of DE1121
Adding useAsToken property to QueryParams.
> Adding useAsToken property to QueryParams.

- pom.xml
> [US6488]: Fixed artifactory repositry references.

- agility.api/src/main/java/com/servicemesh/agility/api/service/StoreProductOperations.java
- agility.sdk-service/pom.xml
- agility.sdk-service/src/main/resources/META-INF/MANIFEST.MF
Also synced to 10.2.1 0dafa5771c74400f9ffac2c000df0223186aff47
> Rev service sdk

- agility.api/pom.xml
- agility.cloud.sdk/pom.xml
- agility.core/pom.xml
- agility.service.sdk/pom.xml
including XSD files in artifact as these are needed for at least one client, agility.
> US9445: including XSD files

- agility.api/src/main/java/com/servicemesh/agility/api/service/IService.java
> added patch method to IService

- agility.api/src/main/java/com/servicemesh/agility/api/service/IService.java
@nialet 
added change to open source develop branch.
> add patch method to IService

- agility.service.sdk/src/main/resources/schema/connection.xsd
- agility.service.sdk/src/main/resources/schema/instance.xsd
> Add variables list to ConnectionRequest, InstanceRequest for DE1734

- agility.api/src/main/resources/schema/enumerations.xsd
- agility.api/src/main/resources/schema/proxy.xsd
- agility.io/src/main/java/com/servicemesh/io/http/HttpVersion.java
- agility.io/src/main/java/com/servicemesh/io/proxy/Proxy.java
- agility.io/src/main/java/com/servicemesh/io/proxy/impl/HttpProxySetupHandler.java
- agility.io/src/main/java/com/servicemesh/io/proxy/impl/ProxyHost.java
- agility.io/src/test/java/com/servicemesh/io/http/HttpVersionTest.java
> US10662: Adding HTTP/1.1 support

- agility.api/src/main/resources/schema/script.xsd
> DE2341: Added instanceId to ScriptStatus for SCRIPT_EXECUTED notifications to all clients

- agility.io/pom.xml
- agility.io/src/main/java/com/servicemesh/io/http/IHttpClientConfig.java
- agility.io/src/main/java/com/servicemesh/io/http/IHttpClientConfigBuilder.java
- agility.io/src/main/java/com/servicemesh/io/http/impl/DefaultHttpClient.java
- agility.io/src/main/java/com/servicemesh/io/http/impl/DefaultHttpClientConfig.java
- agility.io/src/main/java/com/servicemesh/io/http/impl/DefaultHttpClientConfigBuilder.java
- agility.io/src/test/java/com/servicemesh/io/http/HttpClientConfigTest.java
Requesting these changes to be merged . We need to add the CA cert contents to be added to the TrustManager so that we can establish a HTTPS connection to Swarm Manager VM from Agility Platform using Swarm Service Adapter.
> committing changes for DE2440.

- agility.io/pom.xml
- agility.io/src/main/java/com/servicemesh/io/http/IHttpClientConfig.java
- agility.io/src/main/java/com/servicemesh/io/http/IHttpClientConfigBuilder.java
- agility.io/src/main/java/com/servicemesh/io/http/impl/DefaultHttpClient.java
- agility.io/src/main/java/com/servicemesh/io/http/impl/DefaultHttpClientConfig.java
- agility.io/src/main/java/com/servicemesh/io/http/impl/DefaultHttpClientConfigBuilder.java
- agility.io/src/test/java/com/servicemesh/io/http/HttpClientConfigTest.java
Updating Changes to develop branch  . This Code has been already merged to develop-10.2 branch . 
@rafsanchez @Behnke19 Requesting for reviewing and merging .
>  committing changes for DE2440. (#86)

- agility.service.sdk/src/main/java/com/servicemesh/agility/sdk/service/spi/ServiceAdapter.java
- agility.service.sdk/src/test/java/com/servicemesh/agility/sdk/service/ServiceAdapterTest.java
request was not giving any proxy details . Hence getting the proxy details directly from cloud .
@rafsanchez @Behnke19 Requesting your review .
> -- Getting the proxies from the Cloud .

- agility.service.sdk/src/main/java/com/servicemesh/agility/sdk/service/spi/ServiceAdapter.java
- agility.service.sdk/src/test/java/com/servicemesh/agility/sdk/service/ServiceAdapterTest.java
@Behnke19  requesting to review and approve
> -- Getting the proxies from the Cloud . Updating the changes in develop-10.2 branch

- agility.api/src/main/java/com/servicemesh/agility/api/service/IInstance.java
Note: branch name should be US8739.  Please delete after merge.
> US8739 Add script execution method w/variables

- agility.api/src/main/java/com/servicemesh/agility/api/service/IArtifactRepository.java
- agility.api/src/main/resources/schema/releaseManager.xsd
- agility.service.sdk/src/main/java/com/servicemesh/agility/sdk/service/operations/ArtifactRepositoryManagementOperations.java
- agility.service.sdk/src/main/java/com/servicemesh/agility/sdk/service/spi/IArtifactRepositoryManagement.java
- agility.service.sdk/src/main/java/com/servicemesh/agility/sdk/service/spi/ServiceAdapter.java
- agility.service.sdk/src/main/resources/schema/agilityReferences.xsd
- agility.service.sdk/src/main/resources/schema/artifactrepository.xsd
PR for Cherrypicking Artifactory Adapter rest api changes in develop-10.2 
@Behnke19: Please review and merge
> TA18082 : Cherry Pick:  Committing agility-platform-sdk changes and rest api changes present in develop-10.2

- agility.api/src/main/java/com/servicemesh/agility/api/service/IArtifactRepository.java
- agility.api/src/main/resources/schema/releaseManager.xsd
- agility.service.sdk/src/main/resources/schema/artifactrepository.xsd
> Changes return type to ArtifactBinaries

- agility.api/src/main/java/com/servicemesh/agility/api/service/IArtifactRepository.java
- agility.api/src/main/resources/schema/releaseManager.xsd
- agility.service.sdk/src/main/resources/schema/artifactrepository.xsd
@Behnke19  to review. Cherry pick from develop 10.2
> Fixed the RestApi response

- agility.api/src/main/resources/schema/releaseManager.xsd
Added an extra field service provider id in releaseManager.xsd for ArtifactBinary type
@Behnke19 : Please review and merge
> TA19046: changes for the Response class GetAllArtifactsResponse

- agility.api/src/main/resources/schema/releaseManager.xsd
@Behnke19 : Please review and merge
> Cherry Pick: changes in releaseManager.xsd for GetAllArtifactsResponse class 

- agility.api/src/main/resources/schema/releaseManager.xsd
Cheery picked from develop-10.2
> for TA19984 Added artifact mapping structure for Artifactory

- agility.cloud.sdk/src/main/resources/schema/enumerations.xsd
> hostAffinity Property is added

- agility.api/src/main/java/com/servicemesh/agility/api/service/IService.java
apply new IService method to 11.1 so Agility automerge 11.0.2 to 11.1 will have what it needs
> add new patch method to Service

- agility.cloud.sdk/src/main/java/com/servicemesh/agility/sdk/cloud/spi/ICloudAction.java
- agility.cloud.sdk/src/main/resources/schema/cloudOperations.xsd
> TA29538 Add messaging and interface for cloud custom action function

- agility.api/src/main/java/com/servicemesh/agility/api/service/ICloud.java
- agility.cloud.sdk/src/main/java/com/servicemesh/agility/sdk/cloud/spi/CloudAdapter.java
> US15719 Add hooks for cloud execute action

- agility.cloud.sdk/src/main/java/com/servicemesh/agility/sdk/cloud/spi/CloudAdapter.java
- agility.cloud.sdk/src/main/java/com/servicemesh/agility/sdk/cloud/spi/ICloudPing.java
- agility.cloud.sdk/src/main/resources/schema/agilityReferences.xsd
- agility.cloud.sdk/src/main/resources/schema/cloudOperations.xsd
- agility.cloud.sdk/src/main/resources/schema/general.xsd
> US15719 Add method to actually ping the cloud

- agility.api/src/main/resources/schema/script.xsd
- agility.cloud.sdk/src/main/java/com/servicemesh/agility/sdk/cloud/spi/CloudAdapter.java
- agility.core/src/main/resources/schema/messaging/messaging.xsd
- agility.core/src/test/java/com/servicemesh/core/async/SleeperService.java
Cherry Pick from release-11.0.2 to develop
> Added User object to request message

- agility.api/src/main/resources/schema/script.xsd
- agility.cloud.sdk/src/main/java/com/servicemesh/agility/sdk/cloud/spi/CloudAdapter.java
- agility.cloud.sdk/src/main/resources/schema/agilityReferences.xsd
- agility.cloud.sdk/src/main/resources/schema/general.xsd
- agility.core/src/main/resources/schema/messaging/messaging.xsd
- agility.core/src/test/java/com/servicemesh/core/async/SleeperService.java
reverted back the earlier changes.
> Adding User object in cloud request to propogate  to cloud adapter.

- agility.api/src/main/resources/schema/propertyDefinition.xsd
- add hidden attribute to PropertyDefinition
I will follow this up with one for 11.0.2
> feature/US15607 

- agility.api/src/main/resources/schema/assetProperty.xsd
Remove hidden flag.  It has been moved to PropertyDefinition.
> US15607-11.0.2

- agility.cloud.sdk/src/main/resources/schema/agilityReferences.xsd
- agility.cloud.sdk/src/main/resources/schema/general.xsd
@Behnke19 @mark-a-johnson for review
> adding atomicInteger for cloud request

- agility.api/src/main/java/com/servicemesh/agility/api/service/ILaunchItemDeployment.java
> TA30115 Add method for checking/setting deployment freeze

- agility.cloud.sdk/src/main/resources/schema/general.xsd
Sorta cherry-picked from release-11.0.2 - guess Vijaya didn't get his original change in the develop branch.
> TA30129 Use correct type for request ID field

- agility.api/src/main/resources/schema/instance.xsd
- agility.cloud.sdk/src/main/resources/schema/enumerations.xsd
> Add property name enumerations for panel controls

- agility.api/src/main/resources/schema/assetProperty.xsd
add the type info annotation to AssetProperty
> addTypeInfoToAssetProperty

- agility.api/src/main/resources/schema/assetProperty.xsd
- agility.api/src/main/resources/sed/assetprop
- pom.xml
> feature/DE4467-release 11.0.3

- agility.api/pom.xml
- agility.api/src/main/java/com/servicemesh/agility/api/activity/service/IActivity.java
- agility.api/src/main/java/com/servicemesh/agility/api/activity/service/IActivityListener.java
- agility.api/src/main/java/com/servicemesh/agility/api/activity/service/IActivityManager.java
- agility.api/src/main/resources/schema/activity.xsd
- agility.api/src/main/resources/schema/common.xsd
- agility.api/src/main/resources/schema/messaging.xsd
- agility.api/src/main/resources/sed/activity.public
- agility.api/src/main/resources/sed/activity.sed_serial
- agility.api/src/main/resources/sed/activity.sedscript
HIMAL-366 Add separate counters for Instances vs. Service Instances
> HIMAL-370 Move Activty API to external API

- agility.api/pom.xml
- agility.cloud.sdk/pom.xml
- agility.core/pom.xml
- agility.distributed.sync/pom.xml
- agility.io/pom.xml
- agility.service.sdk/pom.xml
- pom.xml
Used automation script to make updates this time
> POM updates for 11.3.3
